### ISSUE TITLE
[compile_fixture] Scale must be a constant tensor in quantize / dequantize op.

### ISSUE THREAD

**Issue by markkraay** [NVIDIA/TensorRT-Incubator#102] opened 2024-08-14 17:09 UTC
Related to `compile_fixture` (#37). `test_dequantize` and `test_quantize` fail `compiler.compile` with the following:
Example Code:
```python
        data = [4, 8]
        input_tp = tp.Tensor(data, dtype=tp.int8)
        scale = torch.tensor(0.5, dtype=TORCH_DTYPES[dtype])
        scale_tp = tp.Tensor(scale, dtype=dtype)
        dequantized = compile_fixture(tp.dequantize, input_tp, scale_tp, dtype)
```
Error Msg:
```python
E       tripy.common.exception.TripyException: 
E       
E       --> /tripy/tests/integration/conftest.py:36 in wrapper()
E             |
E          36 |             compiled_func = compiler.compile(*compile_args, **compile_kwargs)
E             | 
E       
E       Scale must be a constant tensor in dequantize op.

tripy/common/exception.py:195: TripyException
```

**Comment by yizhuoz004** [comment] 2024-08-16 17:59
@markkraay Please provide more information to debug this issue.

- Your PR is not merged, can it be reproduced by existing code?
- What is `dtype` here?
- `Scale must be a constant tensor in dequantize op.` Then what is the op instead?

**Comment by yizhuoz004** [comment] 2024-08-16 18:28
The root cause is in `tripy/tripy/backend/compiler_api.py:L515`, compiler uses `full` to create dummy input values for intial compilation. The fixes could be:
1. implement const fold optimization for `Fill` op when shape is constant.
2. The compile_fixture should add an argument to specify which tensors are inputs, while others are Parameters.

**Comment by parthchadha** [comment] 2024-11-22 16:24
Fixed the test that caused this failure. Closing this issue.

**Closed by parthchadha** 2024-11-22 16:24 UTC
